---
- hosts: all
  become: yes
  tasks:
          
  - name: Install Zabbix-agent on RedHat Family
    yum:
      name={{ item }} update_cache=yes
      state=latest
    loop: [ 'zabbix-agent' ]
    when:
      ansible_os_family == "RedHat"

  - name: Install config Zabbix 10.128.0.9
    template:
      src: "setting-web/file/zabbix_agentd.conf"
      dest: "/etc/zabbix_agentd.conf"
    when:
      ansible_os_family == "RedHat"
    

  - name: Start
    systemd:
      name: zabbix-agent
      enabled: yes
      state: restarted
    when:
      ansible_os_family == "RedHat"



  - name: Install Zabbix-agent on Debian Family
    apt:
      name={{ item }} update_cache=yes
      state=latest
    loop: [ 'zabbix-agent' ]
    when:
      ansible_os_family == "Debian"
     
  - name: Install config Zabbix 10.128.0.9
    template:
      src: "setting-web/file/zabbix_agentd.conf"
      dest: "/etc/zabbix/zabbix_agentd.conf "
    when:
      ansible_os_family == "Debian"


  - name: Start
    systemd:
      name: zabbix-agent
      enabled: yes
      state: restarted
    when:
      ansible_os_family == "Debian"
