---
- hosts: all
  become: yes
  tasks:
          
  - name: Install Webs Servers on RedHat Family
    yum:
      name={{ item }} update_cache=yes
      state=latest
    loop: [ 'apache2', 'nginx', 'php', 'libapache2-mod-php' ]
    when:
      ansible_os_family == "RedHat"
    notify: Status Apache
  
  - name: Start
    systemd:
      name: {{ item }}
      state: started
    with_items:
      - apache2 
      - nginx
    when:
      ansible_os_family == "RedHat"



  - name: Install Webs Servers on Debian Family
    apt:
      name={{ item }} update_cache=yes
      state=latest
    loop: [ 'apache2', 'nginx', 'php', 'libapache2-mod-php' ]
    when:
      ansible_os_family == "Debian"
    notify: Status Apache
  - name: Start
      systemd:
      name: {{ item }}
      state: started
    with_items:
      - apache2
      - nginx
    when:
      ansible_os_family == "Debian"
                                                                          
