---
- hosts: all
  become: yes
  tasks:
          
  - name: Install Zabbix-agent and bind and filebeat on RedHat Family
    yum:
      name={{ item }} update_cache=yes
      state=latest
    loop: [ 'zabbix-agent', 'bind9', 'filebeat' ]
    when:
      ansible_os_family == "RedHat"
    notify: Status Zabbix-agent


  - name: Install Zabbix-agent and bind and filebeat on Debian Family
    apt:
      name={{ item }} update_cache=yes
      state=latest
    loop: [ 'zabbix-agent', 'bind9', 'filebeat' ]
    when:
      ansible_os_family == "Debian"
    notify: Status Zabbix-agent

